### ISSUE TITLE
Trackpad设置空白的解决方案

### ISSUE THREAD

**Issue by mmlmml1** [gunslinger23/XPS15-9560-High-Sierra#14]
简单研究了一下，这个问题可能是由于Voodoo内置了kext与系统冲突导致
结局方案如下：
1. 下载最新的VoodooPS2Controller，https://bitbucket.org/RehabMan/os-x-voodoo-ps2-controller/downloads/ ，并解压
2. 将Kext复制到Clover或是S/L/E内
3. 删掉这两个系统内的kext
  sudo rm -rf /System/Library/Extensions/AppleACPIPS2Nub.kext
  sudo rm -rf /System/Library/Extensions/ApplePS2Controller.kext
4. 将压缩包内的org.rehabman.voodoo.driver.Daemon.plist复制到/Library/LaunchDaemons下
5. 将压缩包Release内的VoodooPS2Daemon复制到/usr/bin下
6. 重启电脑，就能看到Trackpad设置了
![image](https://user-images.githubusercontent.com/12138874/34855513-0cec8ca0-f77b-11e7-8629-26a6b66d7df8.png)

PS：我机型是Dell Precision 5520，但是应该与XPS是一样的。

**Comment by VAllens** [comment]
mark

**Comment by mmlmml1** [comment]
@wolflyingSXin 我这边secondary click是正常的。三指的好像不行，但还没研究，正在尝试把一部分10.12的配置抄过来

**Comment by wolflyingSXin** [comment]
@mmlmml1 刚开始玩，我去熟悉熟悉怎么修改，你的好了可以给我你的配置试试不

**Comment by BillTaozi** [comment]
如果是10.12以前的系统版本触摸板正常吗？

**Comment by BillTaozi** [comment]
今天安教程重装了2次，各种试，触摸板依然问题太多，想回到10.11的版本，不知道触摸板在10.11是否能用三指四指，我是小白，买完dell  xps  15 9560  1928*1080  i7 7700HQ后开始研究黑苹果的，望大神见谅，帮帮忙。

**Comment by mmlmml1** [comment]
@BillTaozi 我之前在用10.12的时候，三指拖动是正常的，其他的不怎么用，没试过

**Comment by BillTaozi** [comment]
好的👌，我试试，谢谢您。


发送自我的三星 Galaxy 智能手机。
-------- 原始信息 --------由： Qingyang Hu <notifications@github.com> 日期: 18/1/18  08:26  (GMT+08:00) 收件人： gunslinger23/XPS15-9560-High-Sierra <XPS15-9560-High-Sierra@noreply.github.com> 抄送： BIllTaozi <176357340@qq.com>, Mention <mention@noreply.github.com> 主题： Re: [gunslinger23/XPS15-9560-High-Sierra] Trackpad设置空白的解决方案 (#14) 
@BillTaozi 我之前在用10.12的时候，三指拖动是正常的，其他的不怎么用，没试过

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gunslinger23/XPS15-9560-High-Sierra","title":"gunslinger23/XPS15-9560-High-Sierra","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gunslinger23/XPS15-9560-High-Sierra"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mmlmml1 in #14: @BillTaozi 我之前在用10.12的时候，三指拖动是正常的，其他的不怎么用，没试过"}],"action":{"name":"View Issue","url":"https://github.com/gunslinger23/XPS15-9560-High-Sierra/issues/14#issuecomment-358495902"}}}

**Comment by BillTaozi** [comment]
我昨晚制作了10.13.2的全新安装U盘，成功安装后，启用大神提供的三指四指驱动，目前除了三指不能用以外，四指上滑下滑，左滑右滑可以，触摸板依然是空白，如果换大神教程提供的最新驱动20171130的话发现触控板可以设置但是三指四指均不可用。

**Comment by BillTaozi** [comment]
呃，发现一个三指可用的操作，就是浏览器浏览网页时，三指左右滑动的话可以翻页，就是上下滑动时没反应，这个是我全新安装10.13.2时目前发现的触摸反应，另外四指上下左右滑动可以，就是用的不多，如果三指的上下滑动可行就完美了。

**Comment by BillTaozi** [comment]
现在触摸驱动有更新吗？是否已经解决之前的问题呢？

**Comment by mmlmml1** [comment]
我不怎么习惯用三指拖动，就暂时没继续研究了，主要是为了打开Tap to click。

2018-03-01 8:54 GMT+08:00 BIllTaozi <notifications@github.com>:
